targets:
  $default:
    sources:
      - lib/api/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/api/"
          output_folder: "lib/swagger_generated_code/"
          ignore_headers: true
