name: Update API class with codegen

on:
  workflow_dispatch:
  repository_dispatch:
    types: [api_schema_updated]
    
jobs:
  crete-new-schema-file:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          repository: RamiroGhilino/Backend-Turnero-TAIE
          ref: test # La branch o commit o copiar
          path: backend   # Directorio en el que se clonará el repositorio de backend
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
        
      - name: Create schema.json
        env:
          SECRET_KEY: "turnero_taie"
        run: |
          cd backend
          python3 manage.py spectacular --format openapi-json --file api_model.json
          
      - name: Save schema file for next jobs
        uses: actions/upload-artifact@v3
        with:
          name: api_model
          path: ./backend/api_model.json
      
      - name: Check json file path
        run: |
          cd backend
          ls -a
          
  update-api-with-codegen:
    runs-on: ubuntu-latest
    needs: crete-new-schema-file
    permissions:
      contents: write #Permiso para poder pushear al repo
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          ref: schema-test
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.12
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check files
        run: ls -a
        
      - name: Retrive schema file
        uses: actions/download-artifact@v3
        with:
          name: api_model
          path: ./lib/api/
          
      - name: Check files
        run: ls -a
        
      - name: Run Codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs # Ejecutar codegen
      
      - name: Push New API class
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: schema-test
          commit_message: Modified API model automatically
