name: Update API class with codegen

on:
  repository_dispatch:
    types: [api_schema_updated]
    
jobs:
  crete-new-schema-file:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Checkout backend code
        uses: actions/checkout@v3
        with:
          repository: RamiroGhilino/Backend-Turnero-TAIE
          ref: test # La branch o commit o copiar
          path: backend   # Directorio en el que se clonará el repositorio de backend
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
        
      - name: Create schema.json
        run: |
          cd backend
          python3 manage.py spectacular --format openapi-json --file schema.json
        
      - name: Copy schema.json
        run: mv ./backend/schema.json $GITHUB_WORKSPACE  # Copiar el archivo JSON de schema desde el repositorio de backend al directorio actual
        
  update-api-with-codegen:
    runs-on: ubuntu-latest
    needs: crete-new-schema-file
    permissions:
      contents: write
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          ref: stage

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          
      - name: Install dependencies
        run: flutter pub get

      - name: Run Codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs    # Reemplaza con el comando que necesitas para ejecutar el codegen en el frontend
      
      - name: Push New API class
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: schema-test
          commit_message: Modified API model automatically
          
